backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "evenements" # Used in routes, e.g., /admin/collections/blog
    label: "Évènements" # Used in the UI
    folder: "evenements" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Date et heure", name: "datetime", widget: "datetime" }
      - {
          label: "Type",
          name: "type",
          widget: "select",
          options: 
            - { label: "Yoga", value: "yoga" }
            - { label: "Sonothérapie", value: "sonotherapie" }
            - { label: "Méditation", value: "meditation" }
            - { label: "Ayurvéda", value: "ayurveda" }
        }
      - { label: "Body", name: "body", widget: "markdown", required: "false" }
